--INSERT INTO "bank-property-evaluation-db".currency (id, name) VALUES (1, 'MUR');
--INSERT INTO "bank-property-evaluation-db".currency (id, name) VALUES (2, 'EUR');
--INSERT INTO "bank-property-evaluation-db".currency (id, name) VALUES (3, 'USD');
--INSERT INTO "bank-property-evaluation-db".currency (id, name) VALUES (4, 'GBP');
--INSERT INTO "bank-property-evaluation-db".currency (id, name) VALUES (5, 'ZAR');
--
--INSERT INTO "bank-property-evaluation-db".facility_type (id, name) VALUES (1, 'Revolving ');
--INSERT INTO "bank-property-evaluation-db".facility_type (id, name) VALUES (2, 'Non-revolving');
--
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (1, 'Title Deed');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (2, 'National Identity Card');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (3, 'Building Permits');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (4, 'Birth Certificate');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (5, 'Marriage Certificate');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (6, 'Quotation');
--INSERT INTO "bank-property-evaluation-db".document_type (id, name) VALUES (7, 'Letter of Intent');
--
--
